### ISSUE TITLE
xyz:servers vs. xyz:subdomains

### ISSUE THREAD

**Issue by DanielJDufour** [stac-extensions/web-map-links#1]
Hi. I'm wondering if `xyz:servers` might be a little more intuitive to people who use LeafletJS if it was called `xyz:subdomains`.  I'm not sure about the nomenclature for other libraries.

https://leafletjs.com/reference.html#tilelayer

**Comment by m-mohr** [comment]
- OpenLayers does it completely differently, there it is `{?-?}` (e.g. `{a-f}`) so you need to do some preprocessing anyway to pass it over. 
- If I understand the MapBox docs correctly, there you can actually define different URLs via an array, so in principle you could provide `https://{s}/maps/{z}/{x}/{y}` and then set `xyz:servers` example.org and mirror.cloud.

That's the intention behind it. Thoughts, @DanielJDufour ?

**Comment by DanielJDufour** [comment]
Ah okay.  That makes a lot more sense.  Hmmm... it's sorta tricky because it seems Mapbox and LeafletJS usage of `{s}` is in conflict.  I'm not sure what to think, but I'll give it some thought.

**Comment by m-mohr** [comment]
What we'll do with {s} is that it's just expanded into multiple URLs.

If you have `https://{s}/example` and `xyz:servers` is `["a.com", "b.eu"]` you'll expand that to `["https://a.com/example", "https://b.eu/example"]`
