### ISSUE TITLE
Add PMTiles

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/web-map-links#17]
- href: URL to the .pmtiles "file"
- type: What's a good media type?
- rel: pmtiles
- What other metadata might be useful to specify in the link for visualization purposes?
  - In the OL example `tileSize` is set
  - MapLibre has quite a number of options set: `type` and `encoding` in the source, `source-layer`, `type` and `paint` in the layer

**Comment by m-mohr** [comment]
@bdon

**Comment by bdon** [comment]
* type: if you mean MIME type, Chris has been using `application/vnd.pmtiles` [like here](https://github.com/cholmes/static-ogc-examples/blob/main/linz/buildings/nz-building-collection.json#L82)
* layers: for vector this requires reading the JSON metadata
* type: can be either raster or vector, can be read by reading the binary header (first 127 bytes)

The other useful data is the bounds, center and zoom level, which you can use to "fit" the map to the right area

**Comment by m-mohr** [comment]
Thanks @bdon, that was fast :-)

- (media) type: Great, will use that. Ideally it would be mentioned somewhere in the PMTiles folder.
- layers: Yes, I thought more if people want to select a specific one. 
- (GIS) type: Good pointer, then I'll read the header. 
- bounds/center/zoom level should ideally be implied by the STAC metadata.

What other metadata might be useful to specify in the link for visualization purposes?
- In the OL example `tileSize` is set
- MapLibre has quite a number of options set: `type` and `encoding` in the source, `source-layer`, `type` and `paint` in the layer

If not provided, do they all have resonable defaults or can be read from the PMTiles metadata? Then I'd just use the defaults or read from metadata, but if any of that is required from the implementor we should provide an option via STAC metadata so that visualizations/maps can be generated automatically.

**Comment by bdon** [comment]
@m-mohr the details exposed through the PMTiles metadata are almost 1:1 with TileJSON, so they should share the same code. In fact we need to add a method to make a PMTiles header+metadata look like a TileJSON: https://github.com/protomaps/PMTiles/issues/239

MapLibre `source` objects need to be initialized with `type` - either raster or vector - but the rest of the source properties can be read from TileJSON. And the layers `paint` properties can be built off the `vector_layers` property of TileJSON, though the visualization will be quite primitive

`tileSize` - there is no PMTiles opinion on this, and in many cases you may need to look at the first tile to determine this (assuming it is 100% consistent across the tileset).
It would be most typical to assume tileSize is 256x256 for raster web slippy maps and 512x512 screen pixels for vector tiles

**Comment by m-mohr** [comment]
Thanks, PRs are up, here #18 and in OL STAC: https://github.com/m-mohr/ol-stac/pull/4
