### ISSUE TITLE
The extension on the asset level

### ISSUE THREAD

**Issue by Geosynopsis** [stac-extensions/web-map-links#24]
Is there any plan to extend the extension to the Asset object level? I imagine the use cases where the individual assets are served via some tiling service.

**Comment by m-mohr** [comment]
Could you elaborate a bit more on what you are envisioning?

**Comment by m-mohr** [comment]
Closing as stale. Feel free to comments if you have any updates.

**Comment by christophenoel** [comment]
Hi @m-mohr ,

Reading again [Best Practices](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md), it is not clear to my why the extension extends [Link Object](https://github.com/radiantearth/stac-spec/tree/master/item-spec/item-spec.md#link-object) and not [Assets object](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#assets).

Assets defines the roles `thumbnail`, `overview` and `visual` are very similar for such purpose. Could you please clarify ?

Thank you very much.
Christophe.

**Comment by m-mohr** [comment]
Assets are usually downloadable objects, while a WMS, XYZ, WCS etc are usually web services and not (fully) downloadable object. As such links as related resources make more sense.

**Comment by christophenoel** [comment]
@m-mohr  IT makes sense. Thank you for the tip :)
