### ISSUE TITLE
How to handle multiple alternative visualizations

### ISSUE THREAD

**Issue by aaime** [stac-extensions/web-map-links#25]
Say that a single product or collection has multiple visualizations, e.g., quality masks, different false color maps, maybe some index computed on the fly (e.g., NDVI). What's the suggested approach to offer such multitude of visualizations?

Is it possible, and recommended, to create multiple links, each one having a "wms" rel, each one offering a different visualization of the same collection/product? 
Or is the specification meant to be used so that only one link with "wms" rel is produced/expected?

**Comment by emmanuelmathot** [comment]
have you checked out https://github.com/stac-extensions/render ?

**Comment by aaime** [comment]
Interesting indeed... but that's not what I'm looking for. For server-side rendered visualizations, is it possible and recommended to use multiple "wms" links, in the context of the web-map-links extension?

**Comment by m-mohr** [comment]
You can have as many e.g. wms links as you like. To further specify their scope, you can use the roles array as recently added to core: https://github.com/radiantearth/stac-spec/pull/1269
