### ISSUE TITLE
Support in stac-pydantic

### ISSUE THREAD

**Issue by jonhealy1** [stac-extensions/web-map-links#26]
There may be some confusion about links and the STAC spec?

https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/issues/247

https://github.com/stac-utils/stac-pydantic/pull/144

**Comment by m-mohr** [comment]
I don't understand the issue?! This is an extension and has no relation to stac-pydantic. Maybe open an issue in their repository? If I misunderstood, please comment with a clarification what the purpose of the issue is. Thanks.
