### ISSUE TITLE
minZoom maxZoom

### ISSUE THREAD

**Issue by DanielJDufour** [stac-extensions/web-map-links#3]
Sometimes tile servers like to restrict the zoom level because the imagery might not have overviews (although in theory all GeoTIFFs in STAC catalog __should__ have overviews).  I'm wondering if it might be helpful to add an `xyz:min-zoom`/`xyz:max-zoom` optional properties.

**Comment by m-mohr** [comment]
We were thinking about it, also for WMTS. For our use case we came up with a different solution, so it's not included here. But happy to add it if there's a need for it. Wondering whether this would better suit into a general "mapping" or "rendering hints" extension though.

See also:
- https://github.com/radiantearth/stac-spec/issues/807
- https://github.com/radiantearth/stac-spec/pull/879

**Comment by DanielJDufour** [comment]
That's a good point, zooming restrictions is really a product of the asset's resolution/size and not the tiler itself, so it makes sense to have in general mapping or rendering hints. I stand corrected :-)
