### ISSUE TITLE
Naming of extension

### ISSUE THREAD

**Issue by rowanwins** [stac-extensions/web-map-links#4]
Hey @m-mohr 

This would certainly be pretty handy!

One thing I'm pondering is the name of `web-map-links` - that name might imply that it takes you to a web-map of the item or collection. It also implies that WMTS and XYZ are related specifically to web maps, but it could also be relevant for other client software like QGIS etc.

So I'm wondering if a better name might be something along the lines of `spatial-api-links`, to me that feels a bit less ambiguous.

Anyway just a suggestion :)

**Comment by m-mohr** [comment]
Thanks @rowanwins for the feedback.

I agree that this could be misleading and people may think this leads to a map, although the name of this extension will only be visible to devs and not to end-users. 

I don't think spatial-api-links is a better term though as this seems to generic. Focus of the extension is getting information transmitted for visualizations on web mapping libraries such as Leaflet, OpenLayers and Mapbox JS.

Thinking about it a bit more: These libraries usually call the entity that is using the information provided by the extension a "source". So maybe it helps if we simply rename to something like "web-map-source-link" or so?

**Comment by cholmes** [comment]
I agree that `spatial-api-links` is too generic, unless we're thinking of including OGC API - Features, and maybe even WFS/WCS. Though those are potentially useful to link to. But if the scope is wmts/xyz/tilejson/ogcapi-tiles then I think `web-map-links` is decent. Could call it `tiled-map-api-links` or something. But I think QGIS users understand they're accessing web maps, indeed WMTS means web map tile service already.
