### ISSUE TITLE
WMS vs WMTS

### ISSUE THREAD

**Issue by rowanwins** [stac-extensions/web-map-links#6]
I'm also wondering if there is a little confusion about WMS vs WMTS.

Things like multiple layers and dimensions are applicable to WMS, however AFAIK WMTS only returns tiles for a single layer and doesn't support dimensions.

The OGC website appears to be down ATM so I can't provide any links, but just wanted to flag it before I forgot :)

**Comment by m-mohr** [comment]
I haven't looked into the WMTS specification yet, but I can certainly specify dimensions in OpenLayers for WMTS and our WMTS servers also support at least a time dimension. I can also expose multiple layers through the WMTS capabilities and add multiple OpenLayers sources with a layer each, so I think the definition works for WMTS. I'm not sure about WMS, haven't worked with it for ages.
